const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "POPKID-MD;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicU5EM0R1enNSS2pHOEYvY0RIZCtJZ2hnWjNLT3QvZzRjRUxNMGtxZUptTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM2g0OW0xZUF6NFlzdVdZUVB1bTcwZDJhbE5KMms3OHU3c0xsczJUbTNGND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJBRUhKbGJ0SE5VeEVmZ3BlR3Q5ZTRzUXY3TEphZDVyU0RuRklqaE45ZkZrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJQZFFLell2Mk9hOERNQllFVWlqaEZEUTZnM2hiREJkaUtFVUQxMGg4UVh3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkVHZEl6MGhQdkJxY2NIWDJZKy9GTUVvREVBcFB0S3VCdU83R0F2d0NFM289In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Imc4WVU3NnI4L1hDZnlsZ1RpMFZvYytUU2hteW1YVVpmQ3VsQ1FEYWd1QjA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidU9CdnFpbitVSXZOMm1LYmpBcVJuSVZOMVFpeUZla2F4TG9ub3pnZ0FXZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUkd0enU0RnF1SVZ6K2QyQ1pCZkVmRE0vVkZrV3AwTm5EUUdncEZRa3NsZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjljU25FMmlWSDJLZGg5Z0dOM0hYN2U0R3A2UjBLN2ZaSnpMa1h4T0FYK3YyWXJPb0ZVeDNyV05yKzJCUm84ajFWR3piaThkemhMY3NmajA3VDcvaGlBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NDMsImFkdlNlY3JldEtleSI6IlhqSkdkT1NFQzR4aUprU25sQlJDQ1Nhc0tHSDZhcnpmdWhmS3BtdE1YNUk9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzU4NDQzMTExQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjZBRTVFMkMxNDhFNjc3RUFFNDhGNTMyMTE4NUJCQjU0In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NDY4NjQzMTN9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IlVWQi10S3J0UUh5WGtDYW1WVm1xU3ciLCJwaG9uZUlkIjoiN2Y0NWQ1MjUtZDdlNC00MDVjLTg1ODgtZjI4ODlkZjNlYzIxIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InpSTGVLSnE0TnFqS2NUYlJ4dEdOOVY1WFZvRT0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ1UkZ2VGdKRW9IVjI1Uk1LOVlHNmhlVE53MDA9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiOUdWOUw4ODgiLCJtZSI6eyJpZCI6IjI1NDc1ODQ0MzExMTo0MUBzLndoYXRzYXBwLm5ldCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDSXltb004Q0VLZVIvTUFHR0FZZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiR3lFWWh1Wk1hSG1uck9RUkQvU0g4TDBZUWYzZGhXNEk0U3JrcDJOVFBrTT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRzBEVkNPT21JVnNmN2VVQU9JK2RQWSswTXhZNU96RWNzekpNSXRRTE9zWlhZSm0rY2U4aWV0eTRKVGtrUjdyeTljam9aVU1ZRWZKK0VGSlpYUHlHQWc9PSIsImRldmljZVNpZ25hdHVyZSI6IjJIenBxSml0V3IrdkJlTXlFNWZyN1p6d2hWVWRieEFWTytOM0VSeXNWYzRWRzFuRDBkeGJubFhEelNBYmFlNkpPLzR3cUVIUUd2bFlOUDVnZ1VCcWp3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzU4NDQzMTExOjQxQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlJzaEdJYm1UR2g1cDZ6a0VRLzBoL0M5R0VIOTNZVnVDT0VxNUtkalV6NUQifX1dLCJwbGF0Zm9ybSI6ImFuZHJvaWQiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NDY4NjQzMDksIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBQ29DIn0=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : true,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false, 
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'false' : false,
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : false, 
  OWNER_REACT: process.env.OWNER_REACT !== undefined ? process.env.OWNER_REACT === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
  AUTO_BIO: process.env.AUTO_BIO !== undefined ? process.env.AUTO_BIO === 'true' : false,
  CHAT_BOT: process.env.CHAT_BOT !== undefined ? process.env.CHAT_BOT === 'true' : false,
  HEART_REACT: process.env.HEART_REACT !== undefined ? process.env.HEART_REACT === 'false' : false,
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  ANTI_DELETE: process.env.ANTI_DELETE !== undefined ? process.env.ANTI_DELETE === 'true' : true,
  MENU_IMAGE: process.env.MENU_IMAGE || "https://i.ibb.co/h0Sw13b/file-1285.jpg",
  BOT_NAME: process.env.BOT_NAME || "Sarkar",
  DELETE_PATH: process.env.DELETE_PATH || "pm",
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "★Ꭿ☼︎ℒ☼︎ℒ✩ℰ✫ℕ♫",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "254758443111",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
